language: php

php:
  - 7.2
  - 7.3

before_script:
  - sh -c "composer install"

script:
    - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

branches:
    only:
        - master

notifications:
    email: false
